version: "3.7"
services:
  # consul
  consul-server:
    image: consul:1.15.4
    # environment:
    #   CONSUL_LOCAL_CONFIG: |
    #     {
    #       "acl": {
    #         "enabled": true,
    #         "default_policy": "deny",
    #         "enable_token_persistence": true,
    #         "tokens": {
    #           "initial_management": "UUID of the initial management token",
    #         }
    #       }
    #     }
    # container_name: consul-server
    restart: always
    volumes:
      - ./consul/data:/consul/data
    #  - ./server.json:/consul/config/server.json:ro
    #  - ./certs/:/consul/config/certs/:ro
    # networks:
    #   - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -data-dir=/consul/data"
networks: 
  default: 
      name: math_bot